### PR TITLE
fix #100

### LINKED ISSUE #100: Couldn't locate libffmpegsumo.so during installation. Audio notifications will be disabled
I'm using Debian Jessie amd64.  I installed plaidchat with npm and got the error:
Couldn't locate libffmpegsumo.so during installation. Audio notifications will be disabled

However I already have chromium installed and the libffmpegsumo file is here:
/usr/lib/chromium/libffmpegsumo.so

### PR DESCRIPTION
**Pull request by Mte90**
I've also added the info for place manually the file if the script cannot found the library.

### CODE REVIEW

File: postinstall.sh [hunk 1]
```diff
@@ -6,9 +6,12 @@ set -x
 # If there is a libffmpegsumo, copy it over
 if test -f /opt/google/chrome/libffmpegsumo.so; then
 	cp /opt/google/chrome/libffmpegsumo.so node_modules/nw/nwjs/libffmpegsumo.so
+elif test -f /usr/lib/chromium/libffmpegsumo.so; then
+	cp /usr/lib/chromium/libffmpegsumo.so node_modules/nw/nwjs/libffmpegsumo.so
 else
 	echo "Couldn't locate libffmpegsumo.so during installation. Audio notifications will be disabled" 1>&2
-	echo "To repair this, please install Google Chrome and reinstall \`plaidchat\`" 1>&2
+	echo "To repair this, please install Google Chrome/Chromium and reinstall \`plaidchat\`" 1>&2
+	echo "Else you can copy the libffmpegsumo.so file in node_modules/nw/nwjs/" 1>&2
```
Comment (twolfson) [inline postinstall.sh]: This line won't be very straightforward to anyone using a non-development version. I would prefer to avoid it and keep it simple with a reinstall.

**Comment by twolfson** [comment]
Looks good except for 1 line which will most likely confuse non-contributors =/

**Comment by twolfson** [comment]
Could we also add in the other Chrome variants mentioned in #100 to truly patch it up?

File: postinstall.sh (hunk 1 above)
Comment (Mte90) [inline postinstall.sh]: i prefer an alert of this type to understand that i can insert the library manually.
In my case on debian sid chromium is not packaged with this library (i do know why) but i can find the library and place it manually.

Comment (twolfson) [inline postinstall.sh]: Right, I know that you can find it. But I am saying that most users will be confused and have no context.

If we want to solve this problem in a more reusable manner (e.g. will still work when we move to a `.deb`/`.rpm` flavor), then maybe we could build a `plaidchat` command that copies over a `.so` file? But I think that would belong in another PR.

```bash
plaidchat install-audio path/to/libffmpegsumo.so
```

Comment (Mte90) [inline postinstall.sh]: okay!

**Comment by twolfson** [comment]
Cool, thanks =) Can you please combine the 2 commits (typically via `git rebase -i`)?

**Comment by Mte90** [comment]
rebased :-)

**Comment by twolfson** [comment]
Great, thanks =D I am busy at the moment but will land this by the end of the weekend. Thanks for your work on this =)

**Comment by twolfson** [comment]
This has been merged/released in `2.10.0`.
